### ISSUE TITLE
Making arrows with -->

### ISSUE THREAD

**Issue by ZeroKun265** [whyt-byte/Blue-Topaz_Obsidian-css#108]
So i switched to Blue Topaz and i like it a lot, but i noticed that there is one cool feature missing.
Just like you can do in the default theme or other themes, i'd like to be able to make short(->), medium(-->) and long(--->) arrows by typing them with dashes and greater/smaller than symbols
They should also work backwards( both like this "-->" and like this"<--")
i think it would make this theme really complete

P.S: I forgot to say that double arrow with ==> would be nice, but aren't as important

**Comment by whyt-byte** [comment]
Thank you for liking the theme! Since I adjusted the font family and letter-spacing, the arrows you want cannot be got in the default Blue Topaz.

**But!** You can install the **Style Settings** plugin and activate the "Use Obsidian Default Font-family" option, then you will get what you want!
![image](https://user-images.githubusercontent.com/72023275/142387917-ac3a47f0-1529-467d-91c5-e74a790ff5e4.png)

You can also use the plugin to change the background images or color schemes to better your Blue Topaz! 

Have fun!

**Comment by ZeroKun265** [comment]
Yep, that worked, thanks :)
