### ISSUE TITLE
cannot keep img-grid style when export to pdf

### ISSUE THREAD

**Issue by sheldonxxd** [whyt-byte/Blue-Topaz_Obsidian-css#269]
![image](https://user-images.githubusercontent.com/42539486/163282148-d76f0dd4-c0ef-4a39-94ea-b76c62dc257f.png)

The "cssclass: img-grid" style works well in Obsidian preview, but the style is missing if exported as PDF.

Meanwhile, wish this style could also support the Live Preview Editing Mode in the lastest Obsidian version.

**Comment by whyt-byte** [comment]
For the YAML cssclass, I think it may be ineffective for exported PDFs, or maybe I haven't found the right way to set it for export.

However, you may choose another way to grid your images. Since you've mastered one "img-grid" method shown above, I am assuming you know or have the DEMO vault (or Example vault, https://github.com/cumany/Blue-topaz-examples). In this case, I suggest you use the Method Two (方法二 in Chinese) to set your images as shown below, i.e. to add `|+grid` behind your images like `![[xxx.png|+grid]]`

## In Obsidian
![image](https://user-images.githubusercontent.com/72023275/163659540-593d1881-bbce-4f81-9659-7a7f3cc64eeb.png)


## PDF
![image](https://user-images.githubusercontent.com/72023275/163659592-26f54b1a-9719-434c-90f9-5198f6588f40.png)

**Comment by sheldonxxd** [comment]
Thanks, it works.
