### ISSUE TITLE
Missing license for Minimal Cards

### ISSUE THREAD

**Issue by kepano** [whyt-byte/Blue-Topaz_Obsidian-css#294]
I noticed that Minimal Cards has been incorporated into Blue Topaz, however there license requirements are missing. You can find the [license here details here](https://github.com/kepano/obsidian-minimal#license). Thanks!

> Minimal is licensed under the MIT License which allows you to modify and redistribute the code, however you must preserve the copyright and license notice in your CSS file. This includes any code you may extract as standalone snippets.
> 
> If you would like to distribute a fork of Minimal or part of its code, please keep my [Buy me a coffee](https://www.buymeacoffee.com/kepano) link present in your Readme.

**Comment by whyt-byte** [comment]
Thank you for telling us. And we are sorry that we didn't notice your license requirements and used part of the code from the Minimal theme. Since I'm not the only contributor to topaz, I don't want to put individual donation channels in the readme. Thus, we've removed the related code mentioned above.

**Comment by LynetteCullens** [comment]
Welp.....That answered my question.
